// ============================================================
// Riley Family — AI Module (OpenAI API)
// Generates member summaries and picks the Family Moment.
//
// Summaries are generated ONCE (by whoever opens the reveal
// first with an API key) then saved to Firebase so every
// other device just reads the result — no key needed.
// ============================================================

window.AI = (() => {

  const CACHE_PREFIX   = 'riley_ai_summary_';
  const FIREBASE_PATH  = 'summaries'; // Firebase path: summaries/{weekKey}/{member}

  // ── Local cache (device-level fallback) ───────────────────

  function lsCacheKey(weekKey, member) {
    return `${CACHE_PREFIX}${weekKey}_${member}`;
  }

  function getLsCache(weekKey, member) {
    try {
      const raw = localStorage.getItem(lsCacheKey(weekKey, member));
      return raw ? JSON.parse(raw) : null;
    } catch { return null; }
  }

  function setLsCache(weekKey, member, data) {
    try { localStorage.setItem(lsCacheKey(weekKey, member), JSON.stringify(data)); } catch {}
  }

  function momentLsKey(weekKey) { return `${CACHE_PREFIX}${weekKey}_MOMENT`; }

  // ── Firebase cache (shared across all devices) ────────────

  async function getRemote(weekKey, member) {
    if (!window.Sync || !Sync.isConfigured()) return null;
    try { return await Sync.get(`${FIREBASE_PATH}/${weekKey}/${member}`); } catch { return null; }
  }

  async function setRemote(weekKey, member, data) {
    if (!window.Sync || !Sync.isConfigured()) return;
    try { await Sync.set(`${FIREBASE_PATH}/${weekKey}/${member}`, data); } catch {}
  }

  // ── Image helper ──────────────────────────────────────────

  function blobToBase64(blob) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  }

  // ── OpenAI API call ───────────────────────────────────────

  async function callOpenAI(messages, systemPrompt = '') {
    const apiKey = CONFIG.OPENAI_API_KEY;
    if (!apiKey) throw new Error('not configured');

    const allMessages = [];
    if (systemPrompt) allMessages.push({ role: 'system', content: systemPrompt });
    allMessages.push(...messages);

    const resp = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model:      CONFIG.OPENAI_MODEL,
        max_tokens: CONFIG.OPENAI_MAX_TOKENS,
        messages:   allMessages,
      }),
    });

    if (!resp.ok) {
      const err = await resp.json().catch(() => ({}));
      throw new Error(err.error?.message || `OpenAI API error ${resp.status}`);
    }

    const data = await resp.json();
    return data.choices?.[0]?.message?.content || '';
  }

  // ── Generate member summary ───────────────────────────────
  // Order of preference:
  //   1. Local localStorage (instant, already on this device)
  //   2. Firebase (generated by another device, synced)
  //   3. Call OpenAI (only if this device has the API key)

  async function generateMemberSummary(weekKey, member, mediaItems) {
    // 1. Local cache
    const local = getLsCache(weekKey, member);
    if (local) return local;

    // 2. Firebase cache — another device may have already generated it
    const remote = await getRemote(weekKey, member);
    if (remote) {
      setLsCache(weekKey, member, remote); // save locally for next time
      return remote;
    }

    // 3. Generate with OpenAI (requires API key on this device)
    const photos = mediaItems.filter(m => m.type === 'photo');
    const videos = mediaItems.filter(m => m.type === 'video');
    const voices = mediaItems.filter(m => m.type === 'voice');

    const content = [];

    const photoLimit = Math.min(photos.length, 4);
    for (let i = 0; i < photoLimit; i++) {
      try {
        const dataURL = await blobToBase64(photos[i].data);
        content.push({ type: 'image_url', image_url: { url: dataURL, detail: 'low' } });
      } catch {}
    }

    let desc = `Family member: ${member}\n`;
    desc += `Media shared this week: ${photos.length} photo(s), ${videos.length} video(s), ${voices.length} voice recording(s).\n`;
    if (videos.length > 0) desc += `They also shared ${videos.length} video(s) this week.\n`;
    if (voices.length > 0) desc += `They recorded ${voices.length} voice message(s) this week.\n`;
    content.push({ type: 'text', text: desc });

    const systemPrompt = `You are a warm, friendly family assistant writing short summaries for a weekly family photo dump app called "Riley Family".
Write a 2–3 sentence summary describing what this family member was up to this week based on their shared media.
Be specific about what you can see in the photos. Keep it warm, positive, and personal.
Use "they" pronouns unless the member is clearly "Dad" or "Mom".
Do not mention the number of photos/videos — focus on the activities and moments visible.
Response should be ONLY the summary sentences, no titles or labels.`;

    const summary = await callOpenAI(
      [{ role: 'user', content: content.length === 1 ? desc : content }],
      systemPrompt
    );

    const result = { summary, generatedAt: Date.now() };

    // Save locally AND push to Firebase so all other devices get it for free
    setLsCache(weekKey, member, result);
    setRemote(weekKey, member, result);

    return result;
  }

  // ── Pick Family Moment of the Week ───────────────────────

  async function pickFamilyMoment(weekKey, allMediaByMember) {
    // 1. Local cache
    const localRaw = localStorage.getItem(momentLsKey(weekKey));
    if (localRaw) { try { return JSON.parse(localRaw); } catch {} }

    // 2. Firebase cache
    const remote = await getRemote(weekKey, '_MOMENT');
    if (remote) {
      localStorage.setItem(momentLsKey(weekKey), JSON.stringify(remote));
      return remote;
    }

    // 3. Generate with OpenAI
    const lines   = [];
    const content = [];

    for (const [member, items] of Object.entries(allMediaByMember)) {
      const photos = items.filter(m => m.type === 'photo');
      lines.push(`${member}: ${items.length} total items (${photos.length} photos, ${items.filter(m=>m.type==='video').length} videos, ${items.filter(m=>m.type==='voice').length} voices)`);
      for (let i = 0; i < Math.min(2, photos.length); i++) {
        try {
          const dataURL = await blobToBase64(photos[i].data);
          content.push({ type: 'image_url', image_url: { url: dataURL, detail: 'low' } });
        } catch {}
      }
    }

    content.push({
      type: 'text',
      text: `Family overview:\n${lines.join('\n')}\n\nLook at the photos above and choose the most memorable, heartwarming, or standout moment from this week. Explain in 2-3 sentences why this is the Family Moment of the Week. Be specific about what you see. Format: just the explanation, no labels or titles.`,
    });

    const systemPrompt = `You are a warm family assistant helping the Riley family celebrate their weekly memories. Pick the most special photo moment and describe why it stands out in 2-3 warm, heartfelt sentences. Be specific about what you observe.`;

    let explanation;
    try {
      explanation = await callOpenAI(
        [{ role: 'user', content: content.length > 1 ? content : content[0].text }],
        systemPrompt
      );
    } catch {
      explanation = 'A special week full of shared memories with the people who matter most. 💙';
    }

    const result = { explanation, generatedAt: Date.now() };

    localStorage.setItem(momentLsKey(weekKey), JSON.stringify(result));
    setRemote(weekKey, '_MOMENT', result);

    return result;
  }

  // ── Clear cache for a week ────────────────────────────────

  function clearWeekCache(weekKey) {
    CONFIG.APP.MEMBERS.forEach(member => {
      localStorage.removeItem(lsCacheKey(weekKey, member));
    });
    localStorage.removeItem(momentLsKey(weekKey));
    // Also clear from Firebase
    if (window.Sync && Sync.isConfigured()) {
      Sync.remove(`${FIREBASE_PATH}/${weekKey}`);
    }
  }

  // ── Public API ────────────────────────────────────────────
  return { generateMemberSummary, pickFamilyMoment, clearWeekCache };

})();
